spring.application.name=bitcoin-gambler

spring.datasource.url=jdbc:postgresql://localhost:5432/bitcoin_gambler
spring.datasource.username=postgres
spring.datasource.password=DEIN_PASSWORT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true